### ISSUE TITLE
target="_blank" ui-sref's with slashes get converted to `%2F` (even when using custom param type)

### ISSUE THREAD

**Issue by mismith** [angular-ui/ui-router#1741]
Using the following custom type:

```
    // fix '/' rewriting to '%2F'
    $urlMatcherFactoryProvider.type('UriPath', {
        encode: function(v){ return v || ''; },
        decode: function(v){ return v || ''; },
        is:     function(v){ return true; },
    });
```

The following:

```
<a ui-sref="page({path: 'lots/of/slashes'})" target="_blank">Click me</a>
```

Opens the following / generates the following `href`:

```
/lots%2Fof%2Fslashes
```

Where I would expect:

```
/lots/of/slashes
```

Live plnkr showing this bug: http://plnkr.co/edit/7WbNArmXm2p3scQUzWHh?p=preview

The expected behaviour does seem to work when there is no `target="_blank"` attribute on the link. How can I work around this?

**Comment by derzwen** [comment]
I have the same problem as well, but always. It doesn't matter if there's a target="_blank" oder not.

If i open your provided punkr, i always see the encoded URLs independent of the target attribute. How did you get this working without a target attribute? From my point of view, it never works....

**Comment by mismith** [comment]
Any update on this?

**Comment by mismith** [comment]
Simplified plunkr from #1119: http://plnkr.co/edit/tNlRmadZRUGRPHhrKqTQ?p=preview

**Comment by jomonkj** [comment]
+1 i have same problem

**Comment by jomonkj** [comment]
solved by this http://jsfiddle.net/jylinman/rm1Lbptf/1/

**Comment by mismith** [comment]
@jomonkj that fiddle does not solve the problem for me on Chrome 44.0.2403.89 for Mac OS X 10.10.4
(see both hovered URL at bottom left and raw URL next to link) ![image](https://cloud.githubusercontent.com/assets/638816/8963128/ad587b90-35db-11e5-8e7e-28c2cdf6853c.png)

**Comment by jomonkj** [comment]
@mismith  you are correct. jsFiddle code only work with firefox. Issue remains with IE and Chrome

**Comment by mismith** [comment]
Still need a solution, despite #1119, #1645, and many others.. I would love to help, but it requires core changes that I don't think I'd be able to make without at least some kind of approval from someone on the ui-router team

**Comment by paveleremin** [comment]
@mismith :+1: for the report, I have the same issue. Did you resolve it some how?

**Comment by vaibhavjn** [comment]
@mismith Getting the same issue, you found any solution for this ?

**Comment by christopherthielen** [comment]
This is addressed in 1.0 using `raw` parameter or parameter types.

http://plnkr.co/edit/bOEIgRN4SHD8mpaMko2W?p=preview
