### ISSUE TITLE
Bugfix in the legacy codebase

### ISSUE THREAD

**Issue by zeusdeux** [angular-ui/ui-router#3027]
Would y'all be ok with a PR that is based on `legacy` branch?

The PR will address an issue with `ui-sref` where it incorrectly discards the promise returned by  `$state.go` and doesn't handle promise rejection.

It will also fix the erroneous behaviour outlined in #2123 if the state transition was triggered by `ui-sref` directive. Also, the change will be isolated to `stateDirective.js` so it shouldn't impede current dev efforts in any way.

Thanks!

**Comment by christopherthielen** [comment]
yep! Is the issue fixed in 1.0 already?  If not, I'd like a PR for both `master` and `legacy`

**Comment by zeusdeux** [comment]
[From the looks of it](https://github.com/angular-ui/ui-router/blob/master/src/ng1/directives/stateDirectives.ts#L67) it isn't fixed on master yet. 

I am unsure that my solution would apply to 1.0 though since it involves triggering a state change event. More specifically `$stateChangeCancel` when a transition is superseded.

**Comment by christopherthielen** [comment]
> More specifically $stateChangeCancel when a transition is superseded.

Interesting... although it doesn't seem like that should be handled by the ui-sref directive.  It seems like the `transitionTo` should be doing that.  

Can you explain fully what the issue you're solving is?

**Comment by zeusdeux** [comment]
I would absolutely love it if `transitionTo` broadcasted `$stateChangeCancel` on `$rootScope` when it rejects with `TransitionSuperseded`. The reasons why I chose not to do it in `transitionTo` are:

1. `transitionTo` method is quite involved and it is quite easy to introduce a bug in it
2. it would change `$stateChangeCancel` trigger semantics across the board
3. I wanted to keep the approach more silo-ed so that it didn't impact part of the codebase I don't know

Now, the issue I am trying to solve is quite straightforward. I am in some state `A` and I start a transition to state `B`. Before the transition to `B` completes, I transition back to `A`. In this scenario, in the legacy world, I am not notified of anything _and_ the locals for state `B` are resolved anyway. None of the `$stateXYZ` nor `$viewContentXYZ` events fire. As a consumer of the api, if I want to do something as simple as show a loader between transitions, the current behaviour would lead to the loader being stuck since no event is fired to notify me that the transition was cancelled.

**Comment by zeusdeux** [comment]
@christopherthielen Any thoughts?

Thanks!

**Comment by christopherthielen** [comment]
@zeusdeux I commented on your PR that I'd like to implement this correctly in `transitionTo`.
I'll put it on a ilestone for a legacy 0.3.2 release.  I'm happy to help you update your PR, or you can wait until I get around to doing it myself.

**Comment by zeusdeux** [comment]
@christopherthielen I went ahead and PR-ed the implementation in `transitionTo` (#3039). I would love for you to take a look :)

Thanks!

**Comment by christopherthielen** [comment]
closed by 	ca7c366
