### ISSUE TITLE
Nested ui-view calls directive's $onInit twice

### ISSUE THREAD

**Issue by esinek** [angular-ui/ui-router#3224]
Using a parent-child hierarchy with nested ui-views, I am having my directive's $onInit being called twice. I've created a SO post for this
http://stackoverflow.com/q/41269277/156611

and also a couple plunkers. One without named views, one with named views.
http://plnkr.co/edit/rc8vbt?p=preview
http://plnkr.co/edit/PZnA5h?p=preview

Is this an issue with how I'm structuring the code or an issue with ui-router?

**Comment by christopherthielen** [comment]
This was fixed by https://github.com/angular-ui/ui-router/pull/3164

The initial content gets linked twice, IIRC.

http://plnkr.co/edit/JjNmK2?p=preview

**Comment by d4guru** [comment]
Hi, 
I have downloaded the last version `@version v0.4.2` but I still get my directive called twice when inside nested `<ui-view>` which version do I have to download to make it work ?

Thank you

**Comment by christopherthielen** [comment]
@d4guru the fix was in [0.4.0](https://github.com/angular-ui/ui-router/releases/tag/0.4.0)

If it's still not working, I need a way to reproduce the error. I suspect you might have a bug in your application causing the behavior.
