### ISSUE TITLE
Make ui-sref-active lazy load friendly

### ISSUE THREAD

**Issue by whitneyit** [angular-ui/ui-router#915]
I've been doing some work with making my an app completely dynamic and I've found that the internal stack of `states`, though updated upon dynamically loaded states, does not have its changes reflected in the uiSrefActive directive.

In the [$stateChangeSuccess](https://github.com/angular-ui/ui-router/blob/91a568454cc600aa4f34dedc8a80c9be1130b1c5/src/stateDirectives.js#L209) update function, by simply adding the following code, it all instantly stated to work;

```js
function update() {

    var ref;

    if (!state) {
        ref = parseStateRef($attrs.uiSref);
        state = $state.get(ref.state, stateContext($element));
    }

    if ($state.$current.self === state && matchesParams()) {
    ...
}
```

Cheers guys and keep up the good work!

**Comment by whitneyit** [comment]
After looking through my open issues I discovered that I have left this open for almost a year :(

I did some investigation and found that this issue was fixed in [bf163ad](https://github.com/angular-ui/ui-router/commit/bf163ad6ce176ce28792696c8302d7cdf5c05a01) and the relevant tests are in [stateDirectiveSpec.js](https://github.com/angular-ui/ui-router/blob/bf163ad6ce176ce28792696c8302d7cdf5c05a01/test/stateDirectivesSpec.js) on lines [347](https://github.com/angular-ui/ui-router/blob/bf163ad6ce176ce28792696c8302d7cdf5c05a01/test/stateDirectivesSpec.js#L347) and [361](https://github.com/angular-ui/ui-router/blob/bf163ad6ce176ce28792696c8302d7cdf5c05a01/test/stateDirectivesSpec.js#L361).

Closing due to this now being a non issue.

**Comment by kasperlewau** [comment]
I'm late to the party but this is still an issue on my end. The setup I'm using looks like the following: 

* A mother abstract `root` state (non-lazy). 
* Several lazy states registered with [ct.ui.router.extras.future](https://github.com/christopherthielen/ui-router-extras/blob/master/src/future.js).
  * Upon navigating to either of the lazy states - [ocLazyLoad](https://github.com/ocombe/ocLazyLoad) will load up the specified module and register a new $state. 
  * All of this is running with [jspm](https://github.com/jspm/jspm-cli) and [SystemJS](https://github.com/systemjs/systemjs). 

--- 

[$$setStateInfo](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L4160) will not find the lazy state in the initial stack of registered states, `state` will evaluate to `null` on `$stateChangeSuccess` in [isMatch()](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L4181) and the active class will only be applied if the referenced state was available in the initial stack. 

Adding the code that @whitneyit posted to the `update()` function, made it work on my end.

---

Here's a [contrived gist](https://gist.github.com/kasperlewau/4b3afa5587a55ccd7481) (*sorry, the file order is all over the place*), of what my setup looks like and of the [modification](https://gist.github.com/kasperlewau/4b3afa5587a55ccd7481#file-modifieduisrefactive-js-L24) made.

(The mod worked in both `update` and `isMatch` in my case, but with the [latest changes in master](https://github.com/angular-ui/ui-router/blob/master/src/stateDirectives.js#L254) I'll take a stab in the dark and say that `update` would be the preferred place to put this). 

Here's some logging info from doing the following: 
* Boot up the application on `/roster`.
* Navigate to `/about`. 

```js
// root.home on initial load
angular-ui-router.js:1938 $$setStateInfo.newState => root.home
angular-ui-router.js:1940 $$setStateInfo.$state.get(newState) => Object {url: "/", views: Object, name: "root.home", $$state: function}
angular-ui-router.js:1957 isMatch.state => Object {url: "/", views: Object, name: "root.home", $$state: function}
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  Object {url: "/", views: Object, name: "root.home", $$state: function}

// root.roster on initial load (this is the state we opened up the application on)
angular-ui-router.js:1938 $$setStateInfo.newState => root.roster
angular-ui-router.js:1940 $$setStateInfo.$state.get(newState) => Object {url: "/roster", views: Object, name: "root.roster", $$state: function}
angular-ui-router.js:1957 isMatch.state => Object {url: "/roster", views: Object, name: "root.roster", $$state: function}
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  Object {url: "/roster", views: Object, name: "root.roster", $$state: function}

// root.about (lazy loaded state, not yet registered as a full-fletched $state)
angular-ui-router.js:1938 $$setStateInfo.newState => root.about
angular-ui-router.js:1940 $$setStateInfo.$state.get(newState) => null
angular-ui-router.js:1957 isMatch.state => null
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  null

// root.streams (lazy loaded state, not yet registered as a full-fletched $state)
angular-ui-router.js:1938 $$setStateInfo.newState => root.streams
angular-ui-router.js:1940 $$setStateInfo.$state.get(newState) => null
angular-ui-router.js:1957 isMatch.state => null
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  null

// $stateNotFound logged as the target (root.about) is not yet registered as a $state
angular.js:4850 event, unfoundState, fromState, fromParams Object {name: "$stateNotFound", targetScope: Scope, preventDefault: function, defaultPrevented: false, currentScope: Scope} Object {to: "root.about", toParams: Object, options: Object} Object {url: "/roster", views: Object, name: "root.roster", $$state: function} Object {}

// matcher for root.home (loaded on init)
angular-ui-router.js:1957 isMatch.state => Object {url: "/", views: Object, name: "root.home", $$state: function}
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  Object {url: "/", views: Object, name: "root.home", $$state: function}

// matcher for root.roster (loaded on init)
angular-ui-router.js:1957 isMatch.state => Object {url: "/roster", views: Object, name: "root.roster", $$state: function}
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  Object {url: "/roster", views: Object, name: "root.roster", $$state: function}

// matcher for root.about (the target, not loaded on init, now loaded but state references the initial boot value)
angular-ui-router.js:1957 isMatch.state => null
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  Object {url: "/about", views: Object, name: "root.about", $$state: function}

// matcher for root.streams (still not loaded, working as expected)
angular-ui-router.js:1957 isMatch.state => null
angular-ui-router.js:1958 isMatch.$state.get(parseStateRef) =>  null
```

*Apologies for the wall of text, but I think the logging of events give a clearer picture of what is going on*. 

If it helps, I can push a more full fletched example with a more in depth report of the problem. 

I do think the issue is still at large - or I'm doing something *terribly* wrong : )

**Comment by whitneyit** [comment]
Are you able to put this into a codepen to demonstrate the problem. My review from a few months ago concluded that it seemed to be working for my use cases and that I found the appropriate tests.

I'm gonna reopen this pending further investigation.

**Comment by kasperlewau** [comment]
I'll see what I can do, for the time being I have to get back to work though. Lunch is over, I'm afraid. Hopefully I'll have a (non)working example up by tonight.

**Comment by whitneyit** [comment]
That's fine. If you can provide a non working feature then I can start work
on a PR :)

Regards,
James

**Comment by kasperlewau** [comment]
@whitneyit I've setup a jsBin that illustrates the problem. Pop open the console and you'll see the output of successful state transitions between `root.home` (registered in main app, non-lazy) and a lazy loaded state - `home.about`. 

At the very end of the jsBin I've commented out the following line; 
```js
//app.config(whitneyMod(app));
```

Uncomment that line, re run and try to navigate to the lazy loaded state. The active class should now be applied to the ui-sref element, and the `classList` directive output would change. 

Here's the bin: http://jsbin.com/fememinina/5/edit

**Comment by kasperlewau** [comment]
I took the liberty of creating a PR(#1884), do feel free to comment and/or improve upon it @whitneyit - I hope you don't mind (I was somewhat bored after getting off of work).

**Comment by whitneyit** [comment]
Awesome mate. I'll have a look when I get into the office

Regards,
James

**Comment by whitneyit** [comment]
@kasperlewau No problem mate. Well done :smile:
